const products = [
  {
    id: 1,
    image: "https://prd.place/400/400?id=buynsell05152505",
    name: "iPhone 16 Pro Max",
    description: "12GB RAM + 256GB Storage",
    category: ["electronics", "smartphone"],
    price: 7000,
    storeDiscountPercentage: 10,
    storeName: "PowerMac",
    stocks: 10,
    rating: 4,
    sold: 52,
  },
  {
    id: 2,
    image: "https://prd.place/400/400?id=buynsell05152504",
    name: "Nike Air Max 270",
    description: "Men's Running Shoes",
    category: ["fashion", "footwear"],
    price: 3000,
    storeDiscountPercentage: 0,
    storeName: "Nike Official",
    stocks: 30,
    rating: 4.6,
    sold: 48,
  },
  {
    id: 3,
    image: "https://prd.place/400/400?id=buynsell05152503",
    name: "Instant Pot Duo 7-in-1",
    description: "Electric Pressure Cooker, 6 Qt",
    category: ["kitchen", "appliance"],
    price: 1500,
    storeDiscountPercentage: 20,
    storeName: "Home Essentials",
    stocks: 12,
    rating: 4.4,
    sold: 50,
  },
  {
    id: 4,
    image: "https://prd.place/400/400?id=buynsell05152502",
    name: "The Subtle Art of Not Giving a F*ck",
    description:
      "A Counterintuitive Approach to Living a Good Life - Mark Manson",
    category: ["books", "self-help"],
    price: 500,
    storeDiscountPercentage: 5,
    storeName: "National Bookstore",
    stocks: 50,
    rating: 3,
    sold: 53,
  },
  {
    id: 5,
    image: "https://prd.place/400/400?id=buynsell05152501",
    name: "Logitech MX Master 3S",
    description: "Wireless Performance Mouse with Quiet Clicks",
    category: ["tech", "accessory"],
    price: 5499,
    storeDiscountPercentage: 10,
    storeName: "Logitech Official",
    stocks: 20,
    rating: 2,
    sold: 47,
  },
  {
    id: 6,
    image: "https://prd.place/400/400?id=buynsell05152500",
    name: "Samsung Galaxy S24 Ultra",
    description: "16GB RAM + 512GB Storage",
    category: ["electronics", "smartphone"],
    price: 8000,
    storeDiscountPercentage: 12,
    storeName: "Samsung Store",
    stocks: 15,
    rating: 4.7,
    sold: 51,
  },
  {
    id: 7,
    image: "https://prd.place/400/400?id=buynsell05152499",
    name: "Adidas Ultraboost 22",
    description: "Performance Running Shoes",
    category: ["fashion", "footwear"],
    price: 3800,
    storeDiscountPercentage: 18,
    storeName: "Adidas Originals",
    stocks: 25,
    rating: 1,
    sold: 49,
  },
  {
    id: 8,
    image: "https://prd.place/400/400?id=buynsell05152498",
    name: "Sony WH-1000XM5",
    description: "Wireless Noise-Canceling Headphones",
    category: ["tech", "audio"],
    price: 1999,
    storeDiscountPercentage: 15,
    storeName: "Sony Center",
    stocks: 18,
    rating: 4.9,
    sold: 54,
  },
  {
    id: 9,
    image: "https://prd.place/400/400?id=buynsell05152497",
    name: "Fitbit Charge 6",
    description: "Fitness & Health Tracker",
    category: ["wearables", "fitness"],
    price: 3999,
    storeDiscountPercentage: 10,
    storeName: "Fitbit Official",
    stocks: 22,
    rating: 4.3,
    sold: 46,
  },
  {
    id: 10,
    image: "https://prd.place/400/400?id=buynsell05152496",
    name: "Anker PowerCore 20000",
    description: "Portable Charger Power Bank",
    category: ["tech", "accessory"],
    price: 499,
    storeDiscountPercentage: 20,
    storeName: "Anker Store",
    stocks: 40,
    rating: 4.6,
    sold: 50,
  },
];

export default products;